import us from './us.png';
import ru from './ru.png';
import es from './es.png';
import kr from './kr.png';
import de from './de.png';
import ja from './jp.png';
import fr from './fr.png';
import nl from './nl.png';
import pl from './pl.png';
import pt from './pt.png';
import usuk from './US-UK.png';

export const America = us;
export const Russia = ru;
export const Spain = es;
export const Korea = kr;
export const Germany = de;
export const Japan = ja;
export const France = fr;
export const Polish = pl;
export const Netherlands = nl;
export const Portuguese = pt;
export const USAUK = usuk;
