module.exports = {
  full: true,
  plugins: [
    'cleanupAttrs',
    'mergeStyles',
    'inlineStyles',
    'removeDoctype',
    'removeXMLProcInst',
    'removeComments',
    'removeMetadata',
    'removeTitle',
    'removeDesc',
    'removeUselessDefs',
    'removeXMLNS',
    'removeEditorsNSData',
    'removeEmptyAttrs',
    'removeHiddenElems',
    'removeEmptyText',
    'removeEmptyContainers',
    // { removeViewBox: false },
    'cleanupEnableBackground',
    'minifyStyles',
    'convertStyleToAttrs',
    'convertColors',
    'convertPathData',
    'convertTransform',
    'removeUnknownsAndDefaults',
    'removeNonInheritableGroupAttrs',
    'removeUselessStrokeAndFill',
    'removeUnusedNS',
    'cleanupIDs',
    // { cleanupNumericValues: false },
    // { cleanupListOfValues: false },
    'moveElemsAttrsToGroup',
    // { moveGroupAttrsToElems: false },
    'collapseGroups',
    'removeRasterImages',
    'mergePaths',
    'convertShapeToPath',
    'convertEllipseToCircle',
    // { sortAttrs: false },
    'removeDimensions',
    { name: 'removeAttrs', params: { attrs: ['fill', 'stroke'] } },
    // { removeElementsByAttr: false },
    // { addClassesToSVGElement: false },
    // { addAttributesToSVGElement: false },
    'removeStyleElement',
    'removeScriptElement',
  ],
};
