export default {
  en: {
    //OVERVIEW//
    "overview.LicensceAgreement": "License Agreement",
    "overview.BlockWeightt": "Block Weight",
    "overview.Balance": "Balance",
    "overview.EncryptedModal": "Your Wallet Is Not Encrypted!",
    "overview.Suggestion":
      "You really should encrypt your wallet to keep your NXS safe.",
    "overview.Ignore": "Ignore",
    "overview.TakeMeThere": "Take Me There",
    "overview.Transactions": "Transactions",
    "overview.MarketPrice": "Market Price",
    "overview.MarketCap": "Market Cap",
    "overview.CirculatingSupply": "Circulating Supply",
    "overview.24hrChange": "24hr Change",
    "overview.Connections": "Connections",
    "overview.BlockCount": "Block Count",
    "overview.InterestRate": "Interest Rate",
    "overview.StakeWeight": "Stake Weight",
    "overview.Globe": "Globe includes GeoLite2",

    //SENDRECEIVE//
    "sendReceive.SendNexus": "Send NXS",
    "sendReceive.Address": "NXS Address",
    "sendReceive.Amount": "NXS Amount",
    "sendReceive.TableAddress": "Address",
    "sendReceive.TableAmount": "Amount",
    "sendreceive.Message": "Message",
    "sendReceive.Remove": "Remove",
    "sendReceive.Queue": "Queue",
    "sendReceive.ClearQueue": "Clear Queue",
    "sendReceive.SendAll": "Send All",
    "sendReceive.SendNow": "Send Now",
    "sendReceive.AddToQueue": "Add To Queue",
    "sendReceive.EditQueue": "Edit Queue",
    "sendReceive.MyAccount": "My Account",
    "sendReceive.EnterYourMessage": "Enter Your Message",
    "sendReceive.Lookup": "Lookup Address",
    "sendReceive.Name": "Name",
    "sendReceive.Cancel": "Cancel",
    "sendReceive.Yes": "Yes",
    "sendReceive.SendTransaction": "Send Transaction?",
    "sendReceive.SendAllFrom": "Send All Transactions From: ",
    "sendReceive.EditEntry": "Edit This Entry",
    "sendReceive.RemoveFromQueue": "Delete Entry?",
    "sendReceive.No": "No",
    "sendReceive.Total": "TOTAL",
    "sendReceive.From": "FROM",
    "sendReceive.FEE": "FEE",
    "sendReceive.CopyToFeild": "Copy To Field",
    "sendReceive.ClickToEdit": "Click To Edit",

    //TRANSACTIONS//
    "transactions.Transactions": "Transactions",
    "transactions.SearchAddress": "Search Address",
    "transactions.Type": "TYPE",
    "transactions.All": "All",
    "transactions.Receive": "Receive",
    "transactions.Sent": "Sent",
    "transactions.Genesis": "Genesis",
    "transactions.Trust": "Trust",
    "transactions.MinimumAmount": "Min Amount",
    "transactions.TimeSpan": "Time Span",
    "transactions.PastYear": "Past Year",
    "transactions.PastMonth": "Past Month",
    "transactions.PastWeek": "Past Week",
    "transactions.Download": "Download",
    "transactions.TX": "TX Number",
    "transactions.Category": "CATEGORY",
    "transactions.Amount": "AMOUNT",
    "transactions.Account": "ACCOUNT",
    "transactions.Address": "ADDRESS",
    "transactions.Time": "TIME SPAN",
    "transactions.Previous": "Previous",
    "transactions.Next": "Next",
    "transactions.MyAccount": "My Account",
    "transactions.Received": "Received",
    "transactions.AMOUNT": "Amount: ",
    "transactions.TIME": "Time: ",
    "transactions.Loading": "Please wait for the daemon to load",
    "transactions.MyAddress": "My Address",
    "transactions.Page": "Page",
    "transactions.Rows": "Rows",
    //Market//
    "Market.Information": "Market Information",
    "Market.Refreash": "Refresh Market Data",
    "Market.Volume": "Volume",
    "Market.All": "All",
    "Market.Receive": "Receive",
    "Market.Sent": "Sent",
    "Market.Genesis": "Genesis",
    "Market.Trust": "Trust",
    "Market.MinimumAmount": "Min Amount",
    "Market.TimeSpan": "Time Span",
    "Market.PastYear": "Past Year",
    "Market.PastMonth": "Past Month",
    "Market.PastWeek": "Past Week",
    "Market.Download": "Download",
    "Market.TX": "TX",
    "Market.Category": "CATEGORY",
    "Market.Amount": "AMOUNT",
    "Market.Account": "ACCOUNT",
    "Market.Address": "ADDRESS",
    "Market.Time": "TIME",
    "Market.Previous": "Previous",
    "Market.Next": "Next",
    "Market.MyAccount": "My Account",
    "Market.Price": "Price",
    "Market.Volume": "Volume",
    "Market.Open": "Open",
    "Market.Close": "Close",
    "Market.High": "High",
    "Market.Low": "Low",
    "Market.Date": "Date",

    //ADDRESSLOOKUP//
    "AddressBook.AddressBook": "Address Book",
    "AddressBook.Export": "Export Contacts",
    "AddressBook.Import": "Import Contacts",
    "AddressBook.SearchContact": "Search Contact",
    "AddressBook.MyAddresses": "My Addresses",
    "AddressBook.addContact": "Add Contact",
    "AddressBook.Name": "Name",
    "AddressBook.ClickToEdit": "Doubleclick To Edit",
    "AddressBook.PhoneNumber": "Phone Number",
    "AddressBook.Phone": "Phone #",
    "AddressBook.Notes": "Notes",
    "AddressBook.AddAddress": "Add Address",
    "AddressBook.BookEmpty": "Your Addressbook Is Empty",
    "AddressBook.EditContact": "Edit Contact",
    "AddressBook.LocalTime": "Local Time",
    "AddressBook.Cancel": "Cancel",
    "AddressBook.Account": "Account",
    "AddressBook.SearchAccount": "Search By Account",
    "AddressBook.CreateAddress": "Create New Address",
    "AddressBook.Create": "Create",
    "AddressBook.NameOption": "Name (Optional)",
    "AddressBook.AddAddressTO": "Add Address To",
    "AddressBook.Copy": "Click To Copy",
    "AddressBook.Back": "Back",
    "AddressBook.TheirAddresses": "Their Addresses",
    "AddressBook.Address": "Address",
    "AddressBook.Addresses": "Addresses",
    "AddressBook.MyAccount": "My Account",
    "AddressBook.EnterAddressName": "Enter Address Name",
    "AddressBook.Loading": "Please wait for the daemon to load",
    "AddressBook.NoContacts": "No Contacts",
    "AddressBook.NXSAddress": "NXS Address",

    //SETTINGS//
    "Settings.Settings": "Settings",
    "Settings.Application": "Application",
    "Settings.Core": "Core",
    "Settings.Security": "Security",
    "Settings.Style": "Style",
    "Settings.SetFee": "Set Transaction Fee?",
    "Settings.Yes": "Yes",
    "Settings.No": "No",
    "Settings.MinimizeTray": "Minimize to tray",
    "Settings.MinimizeClose": "Minimize on close",
    "Settings.InformationPop": "Information Popups",
    "Settings.UsageData": "Send anonymous usage data",
    "Settings.OptionalFee": "Optional transaction fee (NXS)",
    "Settings.Set": "Set",
    "Settings.DeveloperMode": "Developer Mode",
    "Settings.BackupWallet": "Backup Wallet",
    "Settings.StartUp": "Start at system startup",
    "Settings.ChangesNexTime":
      "Changes to core settings will take effect the next time the core is restarted",

    "Settings.Username": "Username",

    "Settings.IpAddress": "Ip Address",
    "Settings.Port": "Port",
    "Settings.UPnp": "Map port using UPnP",
    "Settings.Socks4proxy": "Connect through SOCKS4 proxy",
    "Settings.ProxyIP": "Proxy IP Address",
    "Settings.ProxyPort": "Proxy Port",
    "Settings.Detach": "Detach database on shutdown",
    "Settings.RestartCore": "Restart Core",
    "Settings.Language": "Language",
    "Settings.English": "English",
    "Settings.Russian": "Russian",
    "Settings.LangButton": "English",

    "Settings.EncryptWallet": "Encrypt Wallet",
    "Settings.Password": "Password",
    "Settings.NewPassword": "New Password",
    "Settings.CannotContain": "Password cannot contain these characters",
    "Settings.Re-Enter": "Re-Enter Password",
    "Settings.PasswordsMatch": "Passwords do not match",
    "Settings.Submit": "Submit",
    "Settings.ViewPrivateKey": "View private key for address",
    "Settings.Address": "Address",
    "Settings.EnterAddressHere": "Enter Address Here",
    "Settings.PrivateKey": "Private Key",
    "Settings.Copy": "Copy",
    "Settings.ImportPrivateKey": "Import Private Key",
    "Settings.AccountName": "Account Name",

    "Settings.Wallpaper": "Select Wallpaper",
    "Settings.RenderGlobe": "Render Globe",

    "Settings.SaveSettings": "Save Settings",
    "Settings.ResetStyle": "Reset Style Settings",
    "Settings.Color": "Color",
    "Settings.Fiat": "Fiat Currency",

    "Settings.EnableMining": "Enable Mining",
    "Settings.EnableStaking": "Enable Staking",
    "Settings.VerboseLevel": "Verbose Level",
    "Settings.SaveSettings": "Save Settings",
    "Settings.ManualDaemonMode": "Manual Daemon Mode",
    "Settings.DDN": "Data Directory Name",
    "Settings.ChangePassword": "Change Password",
    "Settings.PreviousPassword": "Previous Password",
    "Settings.PasswordRequired": "Password Is Required",
    "Settings.NewPasswordIsRequired": "New password is required",
    "Settings.ReEnterPassword": "Re-Enter Password:",
    "Settings.NoMatch": "Passwords do not match",
    "Settings.Submit": "Submit",
    "Settings.LockWallet": "Lock Wallet",
    "Settings.ViewPrivateKeyForAddress": "View private key for address",
    "Settings.EncryptRestart": "Encrypt and Restart",

    //CONSOLE//
    "Console.CoreOutput": "Core Output",
    "Console.Console": "Console",
    "Console.ClearConsole": "ClearConsole",
    "Console.Exe": "Execute",
    "Console.MdMode": "Started In Manual Deamon Mode",
    "Console.CommandsHere": "Enter Console Commands Here (ex: getinfo, help)",

    //TRUSTLIST//
    "TrustList.TrustList": "Trust List",
    "TrustList.Address": "Address",
    "TrustList.InterestRate": "Interest Rate",
    "TrustList.SyncMsg": "Please let your wallet sync with the network",

    //Exchange//
    "Exchange.Exchange": "Exchange",
    "Exchange.ShoutOut": "powered by ShapeShift",
    "Exchange.Precise": "Precise",
    "Exchange.Fast": "Fast",
    "Exchange.Send": "Send",
    "Exchange.TradeAmount": "Trade Amount",
    "Exchange.MinTrade": "Minimum Trade",
    "Exchange.RefundAddress": "Refund Address",
    "Exchange.YouAreSending": "YOU ARE SENDING",
    "Exchange.YouWillReceive": "YOU WILL RECEIVE",
    "Exchange.Receive": "Receive",
    "Exchange.BCAddress": "Blackcoin Address",
    "Exchange.ExecuteTrade": "Execute Trade",
    "Exchange.QUOTE": "Отправить запрос",
    "Exchange.NotAvailible": "That pair is temporarily unavailable for trades",
    "Exchange.TradeExceed": "Trade Maximum Exceeded",
    "Exchange.TradeUnMet": "Trade Minimum Unmet",

    //FOOTER//
    "Footer.Overview": "Overview",
    "Footer.Send": "Send",
    "Footer.Nexus": "NXS",

    "Footer.Transactions": "Transactions",
    "Footer.Market": "Market",
    "Footer.Data": "Data",
    "Footer.Address": "Address",
    "Footer.Book": "Book",

    "Footer.Settings": "Settings",
    "Footer.Console": "Console",
    "Footer.Exchange": "Exchange",
    "Footer.Trust": "Trust",
    "Footer.List": "List",

    //HEADER//
    "Header.StakeWeight": "Stake Weight",
    "Header.InterestRate": "Interest Rate",
    "Header.BlockWeight": "Block Weight",
    "Header.TrustWeight": "Trust Weight",
    "Header.WalletUnencrypted": "Wallet Unencrypted",
    "Header.WalletLocked": "Wallet Locked",
    "Header.UnlockedUntil": "Unlocked until",
    "Header.StakingOnly": "Staking Only",
    "Header.Synched": "Synched",
    "Header.Synching": "Syncing...\nBehind\n",
    "Header.Blocks": "Blocks",
    "Header.DaemonNotLoaded": "Daemon Not Loaded",

    //TOOLTIPS//
    "ToolTip.GettingNextBlock": "Getting Next Block...",
    "ToolTip.SystemStartUP":
      "Automatically start the wallet when you log into your system",
    "ToolTip.MinimizeTheWallet": "Minimize the wallet to the system tray",
    "ToolTip.MinimizeOnClose":
      "Minimize the wallet when closing the window instead of closing it",
    "ToolTip.ShowPopups": "Show Informational Popups",
    "ToolTip.Usage":
      "Send anonymous usage data to allow the Nexus developers to improve the wallet",
    "ToolTip.OptionalFee":
      "Optional transaction fee to include on transactions. Higher amounts will allow transactions to be processed faster, lower may cause additional transaction processing",
    "ToolTip.DevMode":
      "Development mode enables advanced features to aid in development. After enabling the wallet must be closed and reopened to enable those features",
    "ToolTip.EnableMining": "Enable/Disable mining to the wallet",
    "ToolTip.EnableStaking": "Enable/Disable staking on the wallet",
    "ToolTip.Verbose": "Verbose level for logs",
    "ToolTip.MDM":
      "Enable manual daemon mode if you are running the daemon manually outside of the wallet",
    "ToolTip.UserName": "Username configured for manual daemon",

    "ToolTip.Password": "Password configured for manual daemon",
    "ToolTip.IP": "IP address configured for manual daemon",
    "ToolTip.PortConfig": "Port configured for manual daemon",
    "ToolTip.DataDirectory": "Data directory configured for manual daemon",
    "ToolTip.UPnP":
      "Automatically open the Nexus client port on the router. This only works when your router supports UPnP and it is enabled",
    "ToolTip.Socks4":
      "Connect to Nexus through a SOCKS4 proxt (e.g. when connecting through Tor)",
    "ToolTip.IPAddressofSOCKS4proxy": "IP Address of SOCKS4 proxy server",
    "ToolTip.PortOfSOCKS4proxyServer": "Port of SOCKS4 proxy server",
    "ToolTip.Detach": "Detach the database when shutting down the wallet",
    "ToolTip.RenderGlobe": "Render the globe on the Overview page",

    //ALERTS//
    "Alert.Received": "Transaction Received",
    "Alert.Sent": "Transaction Sent",
    "Alert.Genesis": "Genesis Transaction",
    "Alert.TrustTransaction": "Trust Transaction",
    "Alert.regiesteredToThis": "This is an address regiestered to this wallet",
    "Alert.InvalidAddress": "Invalid Address",
    "Alert.Invalid": "Invalid",
    "Alert.AddressAdded": "Address Added",
    "Alert.NoAddresses": "No Addresses",
    "Alert.QueueEmpty": "Queue Empty",
    "Alert.PasswordHasBeenChanged": "Password has been changed",
    "Alert.WalletHasBeenEncrypted": "Wallet has been encrypted",
    "Alert.SettingsSaved": "Settings saved",
    "Alert.TransactionFeeSet": "Transaction Fee Set",
    "Alert.WalletLocked": "Wallet Locked",
    "Alert.WalletBackedUp": "Wallet Backed Up",
    "Alert.InvalidTransactionFee": "Invalid Transaction Fee",
    "Alert.Copied": "Copied",
    "Alert.StyleSettingsSaved": "Style Settings Saved",
    "Alert.NoAmmountSet": "No Ammount Set",
    "Alert.PleaseFillOutField": "Please Fill Out Field",
    "Alert.FutureDate":
      "Unlock until date/time must be at least an hour in the future",
    "Alert.IncorrectPasssword": "Incorrect Passsword",
    "Alert.CoreSettingsSaved": "Core Settings Saved",
    "Alert.ContactsExported": "Contacts Exported",

    //COLORPICKER//
    "Cp.AC1": "Accent Color 1",
    "Cp.AC2": "Accent Color 2",
    "Cp.THC": "Table Header Color",
    "Cp.TTC": "Tooltip Color",
    "Cp.TC": "Text Color",
    "Cp.PBC": "Panel Background Color",
    "Cp.NLC": "Nexus Logo Color",
    "Cp.SIC": "Status Icon Color",
    "Cp.FBC": "Footer Base Color",
    "Cp.FHC": "Footer Hover Color",
    "Cp.FAC": "Footer Active Color",
    "Cp.GC": "Globe Color",
    "Cp.GPC": "Globe Pillar Color",
    "Cp.GAC": "Globe Arch Color",

    //LANGUAGEOPTIONS//
    "Lang.English": "English",
    "Lang.Russian": "Russian",
    "Lang.Spanish": "Spanish"
  }
};
