// Core
export const START_CORE_AUTO_CONNECT = 'START_CORE_AUTO_CONNECT';
export const STOP_CORE_AUTO_CONNECT = 'STOP_CORE_AUTO_CONNECT';

export const GET_INFO = 'GET_INFO';
export const GET_SYSTEM_INFO = 'GET_SYSTEM_INFO';
export const GET_STAKE_INFO = 'GET_STAKE_INFO';
export const GET_BALANCES = 'GET_BALANCES';
export const CLEAR_CORE_INFO = 'CLEAR_CORE_INFO';
export const CLEAR_STAKE_INFO = 'CLEAR_STAKE_INFO';
export const CLEAR_BALANCES = 'CLEAR_BALANCES';

// Overview
export const GET_DIFFICULTY = 'GET_DIFFICULTY';

// Trust
export const GET_TRUST_LIST = 'GET_TRUST_LIST';
export const TOGGLE_SORT_DIRECTION = 'TOGGLE_SORT_DIRECTION';

// Market
export const BITTREX_ORDERBOOK = 'BITTREX_ORDERBOOK';
export const BITTREX_24 = 'BITTREX_24';
export const BINANCE_ORDERBOOK = 'BINANCE_ORDERBOOK';
export const BINANCE_24 = 'BINANCE_24';
export const MARKET_DATA_LOADED = 'MARKET_DATA_LOADED';
export const BINANCE_CANDLESTICK = 'BINANCE_CANDLESTICK';
export const BITTREX_CANDLESTICK = 'BITTREX_CANDLESTICK';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SET_ALERTS = 'SET_ALERTS';
export const SET_TRADEVOL = 'SET_TRADEVOL';
export const SET_THRESHOLD = 'SET_THRESHOLD';

// Transactions Page
export const SET_TXS_ACCOUNT_FILTER = 'SET_TXS_ACCOUNT_FILTER';
export const SET_TXS_ADDRESS_QUERY = 'SET_TXS_ADDRESS_QUERY';
export const SET_TXS_CATEGORY_FILTER = 'SET_TXS_CATEGORY_FILTER';
export const SET_TXS_MIN_AMOUNT_FILTER = 'SET_TXS_MIN_AMOUNT_FILTER';
export const SET_TXS_TIME_FILTER = 'SET_TXS_TIME_FILTER';

export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS';
export const ADD_TRANSACTIONS = 'ADD_TRANSACTIONS';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';

// Common
export const LOCK = 'LOCK';
export const BLOCK_DATE = 'BLOCK_DATE';
export const ADD_RPC_CALL = 'ADD_RPC_CALL';
export const SET_MKT_AVE_DATA = 'SET_MKT_AVE_DATA';
export const SHOW_ENCRYPTION_MODAL = 'SHOW_ENCRYPTION_MODAL';

// Send
export const SELECT_CONTACT = 'SELECT_CONTACT';

// Exchange
export const AVAILABLE_COINS = 'AVAILABLE_COINS';
export const FROM_SETTER = 'FROM_SETTER';
export const TO_SETTER = 'TO_SETTER';
export const MARKET_PAIR_DATA = 'MARKET_PAIR_DATA';
export const UPDATE_EXCHANGE_AMMOUNT = 'UPDATE_EXCHANGE_AMMOUNT';
export const TOGGLE_WITHIN_TRADE_BOUNDS = 'TOGGLE_WITHIN_TRADE_BOUNDS';
export const SET_REFUND_ADDRESS = 'SET_REFUND_ADDRESS';
export const SET_TO_ADDRESS = 'SET_TO_ADDRESS';
export const AVAILABLE_PAIR_FLAG = 'AVAILABLE_PAIR_FLAG';
export const SET_QUOTE = 'SET_QUOTE';
export const GREENLIGHT_TRANSACTION = 'GREENLIGHT_TRANSACTION';
export const TRANSACTION_MODAL_ACTIVATE = 'TRANSACTION_MODAL_ACTIVATE';
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';
export const SET_EMAIL = 'SET_EMAIL';
export const CLEAR_QUOTE = 'CLEAR_QUOTE';
export const TOGGLE_ACYNC_BUTTONS = 'TOGGLE_ACYNC_BUTTONS';

// AddressBook
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const LOAD_ADDRESS_BOOK = 'LOAD_ADDRESS_BOOK';
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const MY_ACCOUNTS_LIST = 'MY_ACCOUNTS_LIST';

// Terminal
export const SET_COMMAND_LIST = 'SET_COMMAND_LIST';
export const SET_CONSOLE_INPUT = 'SET_CONSOLE_INPUT';
export const COMMAND_HISTORY_UP = 'COMMAND_HISTORY_UP';
export const COMMAND_HISTORY_DOWN = 'COMMAND_HISTORY_DOWN';
export const EXECUTE_COMMAND = 'EXECUTE_COMMAND';
export const PRINT_COMMAND_OUTPUT = 'PRINT_COMMAND_OUTPUT';
export const PRINT_COMMAND_ERROR = 'PRINT_COMMAND_ERROR';
export const RESET_CONSOLE_OUTPUT = 'RESET_CONSOLE_OUTPUT';
export const PRINT_CORE_OUTPUT = 'PRINT_CORE_OUTPUT';
export const PAUSE_CORE_OUTPUT = 'PAUSE_CORE_OUTPUT';
export const UNPAUSE_CORE_OUTPUT = 'UNPAUSE_CORE_OUTPUT';

// Settings
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_TEMP_SETTINGS = 'UPDATE_TEMP_SETTINGS';
export const CUSTOMIZE_STYLING = 'CUSTOMIZE_STYLING';
export const RESET_COLORS = 'RESET_COLORS';
export const UPDATE_THEME = 'UPDATE_THEME';

// UI
export const CONTACT_SEARCH = 'CONTACT_SEARCH';
export const SWITCH_SETTINGS_TAB = 'SWITCH_SETTINGS_TAB';
export const SWITCH_CONSOLE_TAB = 'SWITCH_CONSOLE_TAB';
export const CLOSE_WALLET = 'CLOSE_WALLET';

export const CREATE_MODAL = 'CREATE_MODAL';
export const REMOVE_MODAL = 'REMOVE_MODAL';
export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const CREATE_BACKGROUND_TASK = 'CREATE_BACKGROUND_TASK';
export const REMOVE_BACKGROUND_TASK = 'REMOVE_BACKGROUND_TASK';

// Modules
export const LOAD_MODULES = 'LOAD_MODULES';
export const UPDATE_MODULE_STATE = 'UPDATE_MODULE_STATE';

// Updater
export const SET_UPDATER_STATE = 'SET_UPDATER_STATE';

// Others
export const SET_ACTIVE_WEBVIEW = 'SET_ACTIVE_WEBVIEW';
export const BOOTSTRAP_STATUS = 'BOOTSTRAP_STATUS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
